name: Deploy BEDEN Website

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Desplegando en el VPS
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.REMOTE_HOST }}
          username: ${{ secrets.REMOTE_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          timeout: 60s
          connect_timeout: 30s
          script: |
            cd /home/bedenb/htdocs/www.bedenb.com
            git fetch origin
            git reset --hard origin/main
            composer install --no-dev --optimize-autoloader
            npm install
            npm run build
            php artisan migrate --force
            php artisan config:clear
            php artisan cache:clear
            php artisan view:clear
            php artisan route:clear
            php artisan config:cache
            php artisan view:cache
            php artisan route:cache
            chown -R bedenb:bedenb /home/bedenb/htdocs/www.bedenb.com
